# Generated by Django 5.0.3 on 2024-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='year_of',
            new_name='year_from',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
